# Headscale configuration for Synology NAS

# Public URL the clients will hit
# – replace with your own DNS name or static public IP
server_url: https://headscale.example.com

# Internal HTTP listener (Docker will map 443 → 8080)
listen_addr: 0.0.0.0:8080

# gRPC / Noise listener for the headscale CLI
grpc_listen_addr: 0.0.0.0:50443

# Prometheus metrics (kept local only)
metrics_listen_addr: 127.0.0.1:9090

# Control-server private key
private_key_path: /var/lib/headscale/private.key

# Tailnet IP ranges
ip_prefixes:
  - 100.64.0.0/10
  - fd7a:115c:a1e0::/48

# SQLite database location
db_type: sqlite3
db_path: /var/lib/headscale/db.sqlite

# DERP (relay) settings – rely on Tailscale’s public network
derp:
  server:
    enabled: false
  paths: []
  auto_update_enabled: true
  update_frequency: 24h

# Misc behaviour
disable_check_updates: false
ephemeral_node_inactivity_timeout: 30m
node_update_check_interval: 30s

# Logging
log_level: info

# ACL – leave empty for “allow all” until you add a policy file
acl_policy_path: ""

# DNS / MagicDNS
dns_config:
  nameservers:
    - 1.1.1.1
    - 1.0.0.1
  magic_dns: true
  base_domain: headscale.local

# Unix socket for local CLI access inside the container
unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"

# Disable logtail
logtail:
  enabled: false

# TLS cert/key issued by DSM (copy them into the container’s /etc/headscale/)
tls_cert_path: /etc/headscale/fullchain.pem
tls_key_path:  /etc/headscale/privkey.pem

# Disable automatic Let’s Encrypt inside Headscale (DSM handles renewal)
tls_letsencrypt_hostname: ""
tls_letsencrypt_cache_dir: ""
tls_letsencrypt_challenge_type: ""
