version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    user: '1026:65537'
    env_file:
      - ./conf/influxdb.env
    volumes:
      - ./influxdb/influxdb/:/var/lib/influxdb/:rw
      - ./influxdb/influxdb2/:/var/lib/influxdb2/:rw
      - ./conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    user: '1026:65537'
    env_file:
      - ./conf/common.env
      - ./conf/grafana.env
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - ./grafana:/var/lib/grafana

  loxone_to_db:
    build: ./loxone_to_db
    container_name: loxone_to_db
    restart: unless-stopped
    ports:
      - "2000:2000/udp"
    user: '1026:65537'
    env_file:
      - ./conf/common.env
      - ./conf/loxone_to_db.env
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - ./loxone_to_db:/usr/src/app:rw
      - ./loxone_to_db/cache:/usr/local/cargo/registry:rw

  mosquitto:
    image: eclipse-mosquitto:2
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
      - 9001:9001
    user: '1026:65537'
    env_file:
      - ./conf/common.env
    links:
      - grafana
    volumes:
      - ./mosquitto/:/mosquitto/:rw
      - ./mosquitto/data/:/mosquitto/data/:rw
      - ./mosquitto/log/:/mosquitto/log/:rw

  weather_scraper:
    build: ./weather_scraper
    container_name: weather_scraper
    restart: unless-stopped
    user: '1026:65537'
    env_file:
      - ./conf/common.env
      - ./conf/weather_scraper.env
    links:
      - influxdb
      - mosquitto
    volumes:
      - ./weather_scraper:/usr/src/app:rw

  telegraf:
    image: telegraf:latest
    hostname: telegraf
    container_name: telegraf
    restart: unless-stopped
    user: '1026:65537'
    volumes:
    - ./telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mosquitto
    links:
      - influxdb
      - mosquitto
    ports:
    - '8125:8125/udp'

  mqtt-loxone-bridge:
    build: ./mqtt-loxone-bridge
    container_name: mqtt-loxone-bridge
    restart: unless-stopped
    user: '1026:65537'
    env_file:
      - ./conf/common.env
      - ./conf/mqtt-loxone-bridge.env
    links:
      - mosquitto
    volumes:
      - ./mqtt-loxone-bridge:/usr/src/app:rw

  teslamate:
    image: teslamate/teslamate:edge
    container_name: teslamate
    restart: always
    environment:
      - ENCRYPTION_KEY=b2Vsdm5yZHF2cGFrc2w5ZGVucm9xbGVyZXVjYXB1ZWpyYQ== # Replace with your generated key
      - DATABASE_USER=teslamate
      - DATABASE_PASS=adminadmin
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - TZ=Europe/Prague  # Set your timezone
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all
    depends_on:
      - database
      - mosquitto

  database:
    image: postgres:16
    container_name: teslamate-db
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=adminadmin
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  growatt_controller:
    build: ./growatt_controller
    container_name: growatt_controller
    restart: unless-stopped
    user: '1026:65537'
    env_file:
      - ./conf/common.env
    links:
      - mosquitto
      - influxdb
    depends_on:
      - mosquitto
      - influxdb
    volumes:
      - ./growatt_controller:/usr/src/app:rw

volumes:
  cargo-cache:
  teslamate-db:
#  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
  mosquitto-log:

