version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/mongo/data; chown 472:472 /srv/docker/mongo/data
      - /srv/docker/mongo/data:/var/lib/mongo

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - /srv/docker/grafana/data:/var/lib/grafana

  loxone_to_mongo:
    build: ./loxone_to_mongo
    ports: 
      - "2000:2000/udp"
    env_file:
      - 'env.loxone_to_mongo'
    depends_on:
      - mongodb
    volumes:
      - ./loxone_to_mongo:/usr/src/app
    links:
      - influxdb