version: '3'
services:
  mongodb:
    image: mongo:5.0
    env_file:
      - 'env.mongo'
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/var/lib/mongo

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./grafana:/var/lib/grafana

  loxone_to_mongo:
    build: ./loxone_to_mongo
    ports: 
      - "2000:2000/udp"
    env_file:
      - 'env.loxone_to_mongo'
    depends_on:
      - mongodb
    volumes:
      - ./loxone_to_mongo:/usr/src/app
    links:
      - mongodb
