version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    env_file:
      - ./conf/influxdb.env
    volumes:
      - ./influxdb:/var/lib/influxdb
      - ./conf/influxdb.conf:/etc/influxdb/influxdb.conf

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    user: '1000'
    env_file:
      - ./conf/common.env
      - ./conf/grafana.env
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - ./grafana:/var/lib/grafana

  loxone_to_db:
    build: ./loxone_to_db
    ports:
      - "2000:2000/udp"
    env_file:
      - ./conf/common.env
      - ./conf/loxone_to_db.env
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - ./loxone_to_db:/usr/src/app

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 8883:8883
      - 9001:9001
    env_file:
      - ./conf/common.env
    links:
      - grafana
    volumes:
      - ./mosquitto/:/mosquitto/:rw
