version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    user: '1026:65537'
    env_file:
      - ./conf/influxdb.env
    volumes:
      - ./influxdb/influxdb/:/var/lib/influxdb/:rw
      - ./influxdb/influxdb2/:/var/lib/influxdb2/:rw
      - ./conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    user: '1026:65537'
    env_file:
      - ./conf/common.env
      - ./conf/grafana.env
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - ./grafana:/var/lib/grafana

  loxone_to_db:
    build: ./loxone_to_db
    container_name: loxone_to_db
    ports:
      - "2000:2000/udp"
    user: '1026:65537'
    env_file:
      - ./conf/common.env
      - ./conf/loxone_to_db.env
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - ./loxone_to_db:/usr/src/app:rw
      - ./loxone_to_db/cache:/usr/local/cargo/registry:rw

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    user: '1026:65537'
    env_file:
      - ./conf/common.env
    links:
      - grafana
    volumes:
      - ./mosquitto/:/mosquitto/:rw
      - ./mosquitto/data/:/mosquitto/data/:rw
      - ./mosquitto/log/:/mosquitto/log/:rw

  weather_scraper:
    build: ./weather_scraper
    container_name: weather_scraper
    restart: unless-stopped
    user: '1026:65537'
    env_file:
      - ./conf/common.env
      - ./conf/weather_scraper.env
    links:
      - influxdb
    volumes:
      - ./weather_scraper:/usr/src/app:rw


volumes:
    cargo-cache:

